sudo: false
language: android
dist: trusty

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-21
    - sys-img-armeabi-v7a-google_apis-21

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26

    licenses:
      - '.+'
    before_script:
      # Create and start emulator.
      - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a --tag google_apis
      - emulator -avd test -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
    script:
    - ./gradlew build connectedCheck